// Internal link graph from a crawl: orphans, click depth, contextual inbound
// links for service and zone pages, sibling cross-links.
//
//   node tools/link-graph.mjs [http://127.0.0.1:8765] [docs/seo/audit-after.json] [docs/seo/link-graph.md]
//
// Pages come from the crawl file (status 200, in the sitemap). Each page is
// fetched again to split its links: "contextual" = inside <main>, "chrome" =
// header, footer and launcher (the same on every page). Rules (exit 1 if any
// fails):
//   1. No orphan: every page has an inbound link from another page.
//   2. Click depth from / (any link) is at most 3.
//   3. Every service page (/servicios/<x>/) has contextual links from >= 3 other pages.
//   4. Every zone page is linked from the /zonas/ hub body and from >= 1 service page body.
//   5. At most one sibling-site (obra/arq/carpinteria.com.py) link per page.
import { readFile, writeFile } from 'node:fs/promises';

const base = (process.argv[2] || 'http://127.0.0.1:8765').replace(/\/$/, '');
const auditFile = process.argv[3] || 'docs/seo/audit-after.json';
const out = process.argv[4] || 'docs/seo/link-graph.md';
const SIBLINGS = /https:\/\/(?:obra|arq|carpinteria)\.com\.py[^"]*/g;

const audit = JSON.parse(await readFile(auditFile, 'utf8'));
const pages = Object.values(audit.pages).filter((page) => page.status === 200 && page.inSitemap).map((page) => page.path).sort();
const pageSet = new Set(pages);
const normal = (href) => {
  if (!href.startsWith('/') || href.startsWith('//')) return null;
  const path = href.split(/[?#]/)[0];
  return pageSet.has(path) ? path : null;
};

const graph = {};
for (const path of pages) {
  const html = await (await fetch(`${base}${path}`)).text();
  const main = html.match(/<main[\s\S]*?<\/main>/)?.[0] || '';
  const links = (fragment) => new Set([...fragment.matchAll(/<a\s[^>]*href="([^"]+)"/g)].map(([, href]) => normal(href)).filter((target) => target && target !== path));
  graph[path] = { contextual: links(main), all: links(html), siblings: (html.match(SIBLINGS) || []).length };
}

const inbound = (target, kind) => pages.filter((from) => from !== target && graph[from][kind].has(target));
const depth = { '/': 0 };
for (let queue = ['/']; queue.length;) {
  const from = queue.shift();
  for (const to of graph[from]?.all || []) if (!(to in depth)) { depth[to] = depth[from] + 1; queue.push(to); }
}

const problems = [];
const services = pages.filter((path) => /^\/servicios\/[^/]+\/$/.test(path));
const zones = pages.filter((path) => /^\/zonas\/[^/]+\/$/.test(path));
for (const path of pages) {
  if (!inbound(path, 'all').length && path !== '/') problems.push(`${path}: orphan (no inbound link)`);
  if (!(path in depth)) problems.push(`${path}: not reachable from /`);
  else if (depth[path] > 3) problems.push(`${path}: ${depth[path]} clicks from / (max 3)`);
  if (graph[path].siblings > 1) problems.push(`${path}: ${graph[path].siblings} sibling-site links (max 1)`);
}
for (const path of services) {
  const count = inbound(path, 'contextual').length;
  if (count < 3) problems.push(`${path}: contextual links from ${count} pages (min 3)`);
}
for (const path of zones) {
  if (!graph['/zonas/']?.contextual.has(path)) problems.push(`${path}: not linked from the /zonas/ hub body`);
  if (!services.some((service) => graph[service].contextual.has(path))) problems.push(`${path}: not linked from any service page body`);
}

const row = (path) => `| \`${path}\` | ${depth[path] ?? '—'} | ${inbound(path, 'contextual').length} | ${inbound(path, 'all').length} | ${graph[path].contextual.size} | ${graph[path].siblings} |`;
const report = [
  '# Internal link graph',
  '',
  `Generated by \`node tools/link-graph.mjs\` from \`${auditFile}\` (${audit.crawledAt}, ${pages.length} indexable pages).`,
  '"Contextual" = links inside `<main>`; "all" adds the header, footer and launcher, which are the same on every page.',
  '',
  '## Rules',
  '',
  '1. No orphan pages. 2. Click depth from `/` ≤ 3. 3. Every service page gets contextual links from ≥ 3 other pages.',
  '4. Every zone page is linked from the `/zonas/` hub body and from ≥ 1 service page body. 5. At most one sibling-site link per page.',
  '',
  problems.length ? `**${problems.length} problem(s):**\n\n${problems.map((problem) => `- ${problem}`).join('\n')}` : '**All rules pass.**',
  '',
  '## Pages',
  '',
  '| Page | Depth | Contextual in | All in | Contextual out | Sibling links |',
  '|---|---:|---:|---:|---:|---:|',
  ...pages.map(row),
  '',
  '## Contextual inbound links per service and zone page',
  '',
  ...[...services, ...zones].map((path) => `- \`${path}\` ← ${inbound(path, 'contextual').map((from) => `\`${from}\``).join(', ') || '—'}`),
  '',
].join('\n');
await writeFile(out, report, 'utf8');
console.log(problems.length ? `Link graph: ${problems.length} problem(s), see ${out}:\n${problems.map((problem) => `- ${problem}`).join('\n')}` : `Link graph passed: ${pages.length} pages, report in ${out}.`);
process.exit(problems.length ? 1 : 0);
